# NumPy


- Numpy is general-purpose arrary-processing package.
- Numpy was created to work with multidimentional arrays.
- It is the fundamental package for scientific computing with python.
- It is open source library.

# Why Use Numpy?

- In python we have lists that serve that purpose of arrays, but they are slow to process.
- Numpy aims to provide an array object that is up to 50x faster than the python lists.
- The array object in numpy is called ndarray, it provide lot of supporting function that make working with ndarray very easy.
- Arrays are very frequently used in data science, where speed and resources are very important.

In [1]:
!pip install numpy 

In [2]:
#Importing necessary library

In [3]:
import numpy as np 

In [4]:
#Arrary creation

a=np.array(10)
a

array(10)

In [5]:
type(a)

numpy.ndarray

In [6]:
#Zero dimentional array

b=np.array(1)
type(b)

numpy.ndarray

In [7]:
b.ndim

0

In [8]:
#One dimentional array

c=np.array([1,2,3])
c

array([1, 2, 3])

In [9]:
print(type(c))
c.ndim

<class 'numpy.ndarray'>


1

In [10]:
#Two dimentional array

d=np.array([[1,2,3],[3,2,1]])
d

array([[1, 2, 3],
       [3, 2, 1]])

In [11]:
d.ndim

2

In [12]:
#Three dimentional array

e=np.array([[[1,2,3,4],
            [3,2,1,4],
             [5,4,3,5],
            [8,1,4,2]]])

In [13]:
e

array([[[1, 2, 3, 4],
        [3, 2, 1, 4],
        [5, 4, 3, 5],
        [8, 1, 4, 2]]])

In [14]:
e.ndim

3

In [15]:
#Change the data type of array element

a=np.array([10,15,52,54])

In [16]:
a.dtype

dtype('int32')

In [17]:
b=np.array([10,15,12,54], dtype='float')

In [18]:
b.dtype

dtype('float64')

In [23]:
b=np.array([10,15,12,54], dtype='float')
print(b.dtype)
print('hello')
b

float64
hello


array([10., 15., 12., 54.])

# Other ways to creating array

1. arange
2. linspace
3. zeros
4. ones
5. random

In [24]:
a=np.arange(1,4,2)

In [25]:
a

array([1, 3])

In [26]:
b=np.linspace(1,5,15)
b

array([1.        , 1.28571429, 1.57142857, 1.85714286, 2.14285714,
       2.42857143, 2.71428571, 3.        , 3.28571429, 3.57142857,
       3.85714286, 4.14285714, 4.42857143, 4.71428571, 5.        ])

In [27]:
b=np.linspace(1,5,15, retstep=True)
b

(array([1.        , 1.28571429, 1.57142857, 1.85714286, 2.14285714,
        2.42857143, 2.71428571, 3.        , 3.28571429, 3.57142857,
        3.85714286, 4.14285714, 4.42857143, 4.71428571, 5.        ]),
 0.2857142857142857)

In [28]:
z=np.zeros([2,2])
z

array([[0., 0.],
       [0., 0.]])

In [29]:
z=np.zeros([2,3])
z

array([[0., 0., 0.],
       [0., 0., 0.]])

In [30]:
q=np.ones([5,4])
q

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [31]:
r=np.random.rand(5,6)
r

array([[0.44107192, 0.28062779, 0.52714638, 0.97703674, 0.34137784,
        0.96980413],
       [0.14622728, 0.39282786, 0.42835433, 0.6898322 , 0.86417604,
        0.93084435],
       [0.51541058, 0.63718702, 0.33258935, 0.27359499, 0.56147892,
        0.10012546],
       [0.09412596, 0.48100462, 0.32555278, 0.90629709, 0.42785271,
        0.46731815],
       [0.25010357, 0.82594436, 0.27746087, 0.31035735, 0.18602044,
        0.823668  ]])

In [32]:
r=np.random.randint(5, size=10)
r

array([4, 2, 4, 0, 1, 1, 1, 0, 0, 0])

# Slicing and indexing array

In [33]:
a=np.array([[1,2,3],
          [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
# 1
a[0,0]

1

In [35]:
#6
a[1,2]

6

In [36]:
#2,3
a[0,1:]

array([2, 3])

In [37]:
# 2,3 and 5,6
a[0:, 1:]

array([[2, 3],
       [5, 6]])

In [38]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
# 1 and 6

a[[0,1],[0,2]]

array([1, 6])

In [40]:
#3 and 4
a[[0,1],[2,0]]

array([3, 4])

# Reshaping the Arrays

In [41]:
a=np.random.rand(5,2)
a

array([[0.82175225, 0.50914593],
       [0.4841375 , 0.04919866],
       [0.83696932, 0.48212101],
       [0.5134996 , 0.35259057],
       [0.51191414, 0.85721586]])

In [42]:
a.reshape(2,5)

array([[0.82175225, 0.50914593, 0.4841375 , 0.04919866, 0.83696932],
       [0.48212101, 0.5134996 , 0.35259057, 0.51191414, 0.85721586]])

In [43]:
a.reshape(10,1)

array([[0.82175225],
       [0.50914593],
       [0.4841375 ],
       [0.04919866],
       [0.83696932],
       [0.48212101],
       [0.5134996 ],
       [0.35259057],
       [0.51191414],
       [0.85721586]])

In [44]:
a.reshape(1,10)

array([[0.82175225, 0.50914593, 0.4841375 , 0.04919866, 0.83696932,
        0.48212101, 0.5134996 , 0.35259057, 0.51191414, 0.85721586]])

In [45]:
a.reshape(5,-1)

array([[0.82175225, 0.50914593],
       [0.4841375 , 0.04919866],
       [0.83696932, 0.48212101],
       [0.5134996 , 0.35259057],
       [0.51191414, 0.85721586]])

# Aggregate Function

- The python numoy aggregate function are sum, min, max, average, product, median, standerd deviation, variance, percentilem and corrcoef

In [46]:
a

array([[0.82175225, 0.50914593],
       [0.4841375 , 0.04919866],
       [0.83696932, 0.48212101],
       [0.5134996 , 0.35259057],
       [0.51191414, 0.85721586]])

In [47]:
a.mean()

0.5418544835866494

In [48]:
a.min()

0.049198660391648885

In [49]:
a.max()

0.8572158641661763

In [50]:
a.prod()

0.00031949855246040016

In [51]:
a.std()

0.23517834279273986

# Stacking


- Stacking is used to join two different arrays.
- Vertical Stacking
- Horizontal Stacking

In [52]:
a=np.array([1,2,3,4,5])
b=np.array([4,5,6,7,8])

In [53]:
np.hstack([a,b])

array([1, 2, 3, 4, 5, 4, 5, 6, 7, 8])

In [54]:
np.vstack([a,b])

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 7, 8]])